# Generated by Django 5.0.6 on 2024-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                blank=True,
                default="Click on the link below to read full article...",
                max_length=100,
                null=True,
            ),
        ),
    ]
