# Generated by Django 5.0.6 on 2024-07-14 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="header_image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="header_images/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
