# Generated by Django 5.0.6 on 2024-07-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_profile_description_alter_post_header_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="header_images/"),
        ),
    ]
