# Generated by Django 5.0.6 on 2024-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
