# Generated by Django 5.0.6 on 2024-07-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_pushsubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PushSubscription",
        ),
    ]
